os: osx
language: cpp

compiler:
    - clang

before_install:
  - brew install grep
  - |
    if ! git diff --name-only $TRAVIS_COMMIT_RANGE | ggrep 'http-parser'
    then
      echo "SKIP conan build for other packages"
      set +e
      travis_terminate 0
    fi

install:
  - .ci/install.sh

script:
  - conan config install https://github.com/includeos/conan_config.git
  - |
    if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]];
    then
      conan
    fi
    if [ -n "$TRAVIS_TAG" ]; then
      conan search -r includeos
    fi
