<<<<<<< HEAD
#!/bin/bash

set -e
set -x
#ls -A | grep -v src | xargs rm -r || :
if [[ "$(uname -s)" == 'Darwin' ]]; then
    brew update || brew update
    brew install cmake || true
fi
pip install conan --upgrade
pip install conan_package_tools bincrafters_package_tools
conan user
=======
os: osx
language: cpp

compiler:
    - clang

before_install:
  - brew install grep
  - |
    if ! git diff --name-only $TRAVIS_COMMIT_RANGE | ggrep 'binutils'
    then
      echo "SKIP conan build for other packages"
      travis_terminate 0
    fi

install:
  - .ci/install.sh

script:
  - conan config install https://github.com/includeos/conan_config.git
  - conan create dependencies/gnu/binutils/2.31 binutils/2.31@includeos/latest -pr apple-clang-10-macos-toolchain
  - conan search binutils/2.31@includeos/latest
  - |
    if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]];
    then
      conan upload --all binutils/2.31@includeos/latest -r includeos
    fi
    if [ -n "$TRAVIS_TAG" ]; then
      conan copy --all binutils/2.31@includeos/latest includeos/stable
      conan upload --all binutils/2.31@includeos/stable -r includeos
    fi
>>>>>>> 99ec824b8c72c7d7f4b1a8272c88c2d8ab30a317
